### PR TITLE
fix lexing `'\\` to not error in the validate token step

### LINKED ISSUE #232: `EOFError: read end of file` when tokenizing a non finished char literal with backslash
```julia
julia> JuliaSyntax.tokenize("'\\")
ERROR: EOFError: read end of file
Stacktrace:
 [1] read
   @ ./iobuffer.jl:217 [inlined]
 [2] read
   @ ./io.jl:789 [inlined]
 [3] validate_tokens(stream::JuliaSyntax.ParseStream)
   @ JuliaSyntax ~/.julia/packages/JuliaSyntax/EGQXe/src/parse_stream.jl:903
 [4] #parse!#81
   @ ~/.julia/packages/JuliaSyntax/EGQXe/src/parser_api.jl:54
 [5] parse!
   @ ~/.julia/packages/JuliaSyntax/EGQXe/src/parser_api.jl:43 [inlined]
 [6] tokenize(text::String)
   @ JuliaSyntax ~/.julia/packages/JuliaSyntax/EGQXe/src/parser_api.jl:181
 [7] top-level scope
   @ REPL[4]:1
```

Reported in https://github.com/KristofferC/OhMyREPL.jl/issues/314. OhMyREPL assumes that the Tokenize step does not error so it is a regression there vs Tokenize.jl which produces:

```julia
julia> collect(Tokenize.tokenize("'\\"))
2-element Vector{Tokenize.Tokens.Token}:
 1,1-1,2          ERROR          "'\\"
 1,3-1,2          ENDMARKER      ""
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #232

### CODE REVIEW

**Review by c42f — APPROVED** [review]
Looks good to me!

**Comment by KristofferC** [comment]
Do you think the error I chose here is ok? I guess technically, it is not an invalid escape sequence?

**Comment by c42f** [comment]
Yes I think that error is fine - it can be seen as an incomplete escape sequence.

Though now that I look closer, I think the fix is better made inside `unescape_julia_string`.  Let me push that variant up here.

**Comment by pfitzseb** [comment]
Maybe introducing a new error kind (`ErrorEOF` or something like that) makes sense? Could then use that for other incomplete tokens as well, instead of the generic `K"error"`:
```
julia> JuliaSyntax.tokenize(""""foo""")
3-element Vector{JuliaSyntax.Token}:
 JuliaSyntax.Token(JuliaSyntax.SyntaxHead(K""", 0x0001), 0x00000001:0x00000001)
 JuliaSyntax.Token(JuliaSyntax.SyntaxHead(K"String", 0x0000), 0x00000002:0x00000004)
 JuliaSyntax.Token(JuliaSyntax.SyntaxHead(K"error", 0x0001), 0x00000005:0x00000004)
```

**Comment by c42f** [comment]
There, I've pushed the tweak up into `unescape_julia_string` - that way we get the correct diagnostic emitted for strings as well as character literals.

**Comment by c42f** [comment]
If you feel like making a release that's cool (just cherry pick this onto the `release-0.3.3` branch ... which uh.. should have been named `release-0.3`. Because `main` branch has breaking changes right now).

If not I'll do it tomorrow morning.

**Pull request merged**
