### PR TITLE
Separate UUID for the JuliaSyntax in sysimage

### PR DESCRIPTION
**Pull request by c42f**
This allows us to use JuliaSyntax baked into the sysimage to develop
a separate JuliaSyntax with Revise :-D

### CODE REVIEW

**Comment by pfitzseb** [comment]
Fun fact: You can just modify `Base.loaded_modules` after loading the first instances (basically pop the original entry and re-insert it with a modified UUID).

**Comment by c42f** [comment]
Interesting. Is there a way to get this to be permanent when using PackageCompiler to create the sysimage?

**Comment by pfitzseb** [comment]
Good question. I have no idea, tbh :)

**Comment by c42f** [comment]
Ok let's go with this hack, then :)

**Pull request merged**
